/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function getPermissionStatus(appUserModelId?: string | undefined | null): NotificationPermissionStatus

export type NotificationPermissionStatus =
  | 'granted'
  | 'denied'
  | 'not-determined'
  | 'limited'
  | 'unsupported'
  | 'unknown'
