/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function getNotificationCapability(
  options?: NotificationDiagnosticsOptions | undefined | null,
): NotificationCapability

export declare function getNotificationInterruptionLevel(): NotificationInterruptionLevel

export declare function getNotificationPermissionStatus(
  options?: NotificationDiagnosticsOptions | undefined | null,
): NotificationPermissionStatus

export declare function getPermissionStatus(appUserModelId?: string | undefined | null): NotificationPermissionStatus

export interface NotificationCapability {
  canNotify: boolean
  permission: NotificationPermissionStatus
  interruptionLevel: NotificationInterruptionLevel
  reasons: Array<NotificationUnavailableReason>
}

export interface NotificationDiagnosticsOptions {
  appUserModelId?: string
}

export type NotificationInterruptionLevel = 'normal' | 'limited' | 'unsupported' | 'unknown'

export type NotificationPermissionStatus =
  | 'granted'
  | 'denied'
  | 'not-determined'
  | 'limited'
  | 'unsupported'
  | 'unknown'

export type NotificationUnavailableReason =
  | 'permission-denied'
  | 'permission-not-determined'
  | 'missing-app-user-model-id'
  | 'invalid-app-user-model-id'
  | 'unsupported-platform'
  | 'unknown'

export declare function requestMacFocusStatusAuthorization(): NotificationInterruptionLevel

export declare function requestMacNotificationPermission(
  options?: NotificationDiagnosticsOptions | undefined | null,
): NotificationPermissionStatus
