/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function getNotificationCapability(
  options?: NotificationDiagnosticsOptions | undefined | null,
): NotificationCapability

export declare function getNotificationFocusStatus(
  options?: NotificationDiagnosticsOptions | undefined | null,
): NotificationFocusStatus

export declare function getNotificationPermissionStatus(
  options?: NotificationDiagnosticsOptions | undefined | null,
): NotificationPermissionStatus

export declare function getPermissionStatus(appUserModelId?: string | undefined | null): NotificationPermissionStatus

export interface NotificationCapability {
  canNotify: boolean
  permission: NotificationPermissionStatus
  focusStatus: NotificationFocusStatus
  reasons: Array<NotificationUnavailableReason>
}

export interface NotificationDiagnosticsOptions {
  appUserModelId?: string
  platform?: string
  requestFocusAuthorization?: boolean
}

export type NotificationFocusStatus = 'active' | 'inactive' | 'unsupported' | 'unknown'

export type NotificationPermissionStatus =
  | 'granted'
  | 'denied'
  | 'not-determined'
  | 'limited'
  | 'unsupported'
  | 'unknown'

export type NotificationUnavailableReason =
  | 'permission-denied'
  | 'permission-not-determined'
  | 'missing-app-user-model-id'
  | 'invalid-app-user-model-id'
  | 'unsupported-platform'
  | 'unknown'

export declare function requestNotificationPermission(
  options?: NotificationDiagnosticsOptions | undefined | null,
): NotificationPermissionStatus
